# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eladiwmicrosoft/express_sample
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
